const $=s=>document.querySelector(s);let length=5,repeats=false,secret="",guesses=[];
const makeSecret=()=>{const d=[..."0123456789"];if(repeats)return Array.from({length},()=>d[Math.floor(Math.random()*10)]).join("");for(let i=9;i>0;i--){const j=Math.floor(Math.random()*(i+1));[d[i],d[j]]=[d[j],d[i]]}return d.slice(0,length).join("")};
function score(g){let exact=0,s={},x={};for(let i=0;i<length;i++)if(secret[i]===g[i])exact++;else{s[secret[i]]=(s[secret[i]]||0)+1;x[g[i]]=(x[g[i]]||0)+1}return{exact,misplaced:Object.keys(x).reduce((n,d)=>n+Math.min(x[d],s[d]||0),0)}}
function settings(){localStorage.setItem("mstrmnd-settings",JSON.stringify({length,repeats}));$("#rule").textContent=`Crack the hidden ${length}-digit number.`;$("#repeats").classList.toggle("on",repeats);$("#repeats").setAttribute("aria-checked",repeats);$("#guess").maxLength=length;$("#guess").placeholder="•".repeat(length)}
function start(){secret=makeSecret();guesses=[];$("#play").innerHTML='<form id="form"><label id="guess-label" for="guess">Guess #1</label><div class="entry"><input id="guess" inputmode="numeric" pattern="[0-9]*" autocomplete="off" autofocus><button id="check">Check</button></div><p id="error">&nbsp;</p></form>';bind();render();settings();$("#guess").focus()}
function bind(){const input=$("#guess");input.addEventListener("input",()=>{input.value=input.value.replace(/\D/g,"").slice(0,length);$("#error").innerHTML="&nbsp;"});$("#form").addEventListener("submit",e=>{e.preventDefault();const g=input.value;if(g.length!==length)return $("#error").textContent=`Enter exactly ${length} digits.`;if(!repeats&&new Set(g).size!==g.length)return $("#error").textContent="Digits cannot repeat in this game.";const r=score(g);guesses.unshift({g,...r});if(r.exact===length)win();else{input.value="";render();input.focus()}})}
function render(){if(!$("#guess-label"))return;$("#guess-label").textContent=`Guess #${guesses.length+1}`;$("#count").textContent=`${guesses.length} ${guesses.length===1?"attempt":"attempts"}`;$("#list").className=guesses.length?"":"empty";$("#list").innerHTML=guesses.length?guesses.map((v,i)=>`<div class="row"><span>${guesses.length-i}</span><b>${v.g}</b><span class="score"><em>+${v.exact}</em><strong>−${v.misplaced}</strong></span></div>`).join(""):'<i>?</i><p>Your clues will appear here.</p>'}
function win(){render();$("#play").innerHTML=`<section class="victory"><small>CODE CRACKED</small><h2>${secret}</h2><p>You solved it in <b>${guesses.length}</b> ${guesses.length===1?"guess":"guesses"}.</p><button id="again">Play again</button></section>`;$("#again").onclick=start}
for(let n=3;n<=10;n++)$("#length").add(new Option(n,n));try{const s=JSON.parse(localStorage.getItem("mstrmnd-settings"));length=Math.min(10,Math.max(3,s.length||5));repeats=!!s.repeats}catch{}$("#length").value=length;$("#length").onchange=e=>{length=+e.target.value;start()};$("#repeats").onclick=()=>{repeats=!repeats;start()};$("#new").onclick=start;start();if("serviceWorker"in navigator)navigator.serviceWorker.register("sw.js");
